inputs:
  TEST_DATABASE_URL:
    description: 'TEST_DATABASE_URL'
    required: true
runs:
  using: 'Composite'
  steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      - name: redwood test
        run:  |
          export NODE_OPTIONS="--max_old_space_size=4096"
          yarn rw test
        env:
          TEST_DATABASE_URL: ${{ inputs.TEST_DATABASE_URL }}
          SUPABASE_API_URL: ${{ inputs.SUPABASE_API_URL }}
          SUPABASE_ANON_KEY: ${{ inputs.SUPABASE_ANON_KEY }}
        shell: bash
