inputs:
  TEST_DATABASE_URL:
    description: 'TEST_DATABASE_URL'
    required: true
runs:
  using: 'Composite'
  steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      - name: redwood test
        run: yarn rw test
        shell: bash
        env:
          SUPABASE_API_URL: ${{ inputs.TEST_DATABASE_URL }}
