name: chromatic_development

on:
  push:
    branches:
      - develop
    paths:
      - 'web/src/**'

jobs:
  chromatic_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: StorybookTest
        uses: ./.github/actions/sbtest
        with:
          SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      - name: redwood test
        uses: ./.github/actions/jesttest
        with:
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      - name: Chromatic
        uses: ./.github/actions/chromatic
        with:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
