name: redwood_test

on: [push]

jobs:
  redwood_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: redwood test
        uses: ./.github/actions/jesttest
        with:
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      - name: redwood build
        run: yarn rw build
