name: storybook_test

on:
  push:
  workflow_dispatch:

jobs:
  redwood_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: echo OK
  Reuse:
    uses: ./.github/workflows/chromatic_pr_onpush.yml
      # - name: storybook build
      #   run: yarn rw storybook --build
      # - name: storybook test
      #   run: |
      #     cd web
      #     yarn test-storybook:ci
      #   env:
      #     SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
      #     SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
